# Generated by Django 4.2.29 on 2026-03-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='Structured questionnaire answers from the onboarding form.'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='score',
            field=models.IntegerField(default=0, help_text='Computed adopter score based on questionnaire answers.'),
        ),
    ]
