# Generated by Django 4.2.29 on 2026-03-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, default='Mestiza', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(help_text='e.g. "2 años"', max_length=50),
        ),
    ]
