# Generated by Django 4.2.29 on 2026-03-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_breed_alter_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('small', 'Pequeño'), ('medium', 'Mediano'), ('large', 'Grande')], default='medium', max_length=10),
        ),
    ]
